plugins { id 'com.android.application' }

android {
    namespace 'com.ug.e87idrive'
    compileSdk 35

    defaultConfig {
        applicationId "com.ug.e87idrive"
        minSdk 23
        targetSdk 35
        versionCode 19
        versionName "1.9.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
